apiVersion: v1
kind: Pod
metadata:
  name: obsidian
spec:
  containers:
    - name: db
      image: docker.io/library/couchdb:3
      envFrom:
        - configMapRef:
            name: env
      ports:
        - containerPort: 5984
          hostPort: 5984
      volumeMounts:
        - name: db-data
          mountPath: /opt/couchdb/data
        - name: db-config
          mountPath: /opt/couchdb/etc/local.d
          
    - name: bridge
      image: localhost/livesync-bridge:latest
      volumeMounts:
        - name: bridge-config
          mountPath: /app/dat
          readOnly: true
        - name: vaults
          mountPath: /data/obsidian/vaults
        - name: bridge-state
          mountPath: /home/deno/.local/share/deno
          
  volumes:
    - name: db-data
      hostPath:
        path: /data/obsidian/db/data
        type: Directory
    - name: db-config
      hostPath:
        path: /data/obsidian/db/config
        type: Directory
    - name: bridge-config
      hostPath:
        path: /opt/obsidian
        type: Directory
    - name: vaults
      hostPath:
        path: /data/obsidian/vaults
        type: DirectoryOrCreate
    - name: bridge-state
      hostPath:
        path: /data/obsidian/vaults/.deno
        type: DirectoryOrCreate
