apiVersion: v1
kind: Pod
metadata:
  name: dozzle
spec:
  containers:
    - name: server
      image: ghcr.io/amir20/dozzle:v10
      envFrom:
        - configMapRef:
            name: env
      ports:
        - containerPort: 8080
          hostPort: 8080
      volumeMounts:
        - name: data
          mountPath: /data
        - name: podman-socket
          mountPath: /var/run/docker.sock
          readOnly: true
      livenessProbe:
        exec:
          command:
            - "/dozzle"
            - "healthcheck"
        initialDelaySeconds: 5
        periodSeconds: 5
        failureThreshold: 5

  volumes:
    - name: data
      hostPath:
        path: /opt/dozzle/data
        type: DirectoryOrCreate
    - name: podman-socket
      hostPath:
        path: /run/podman/podman.sock
        type: Socket
