apiVersion: v1
kind: Pod
metadata:
  name: jellyfin
spec:
  securityContext:
    supplementalGroups: [44, 993]

  containers:
    - name: server
      image: ghcr.io/jellyfin/jellyfin:10
      envFrom:
        - configMapRef:
            name: env
      ports:
        - containerPort: 8096
          hostPort: 8096
      livenessProbe:
        httpGet:
          path: /health
          port: 8096
        initialDelaySeconds: 30
        periodSeconds: 30
        timeoutSeconds: 5
      volumeMounts:
        - name: config
          mountPath: /config
        - name: cache
          mountPath: /cache
        - name: media
          mountPath: /media
      resources:
        limits:
          memory: "1Gi"
          podman.io/device=/dev/dri/card1: 1
          podman.io/device=/dev/dri/renderD128: 1
        requests:
          memory: "256Mi"

  volumes:
    - name: config
      hostPath:
        path: /data/jellyfin/config
        type: DirectoryOrCreate
    - name: cache
      hostPath:
        path: /data/jellyfin/cache
        type: DirectoryOrCreate
    - name: media
      hostPath:
        path: /data/jellyfin/media
        type: DirectoryOrCreate
