apiVersion: v1
kind: Pod
metadata:
  name: immich
spec:
  securityContext:
    supplementalGroups: [44, 993]

  containers:
    - name: server
      # Edit this line if IMMICH_VERSION in .env file changes
      image: ghcr.io/immich-app/immich-server:v3
      envFrom:
        - configMapRef:
            name: env
      ports:
        - containerPort: 2283
          hostPort: 2283
      livenessProbe:
          httpGet:
            path: /api/server/ping
            port: 2283
          initialDelaySeconds: 30
          periodSeconds: 30
      volumeMounts:
        - name: upload-location
          mountPath: /data
        - name: localtime
          mountPath: /etc/localtime
          readOnly: true
      resources:
        limits:
          podman.io/device=/dev/dri/card1: 1
          podman.io/device=/dev/dri/renderD128: 1

    - name: ml
      # Edit this line if IMMICH_VERSION in .env file changes
      image: ghcr.io/immich-app/immich-machine-learning:v3-openvino
      envFrom:
        - configMapRef:
            name: env
      env:
        - name: MACHINE_LEARNING_MODEL_INTER_OP_THREADS
          value: "1"
        - name: MACHINE_LEARNING_MODEL_INTRA_OP_THREADS
          value: "2"
        - name: MACHINE_LEARNING_WORKER_TIMEOUT
          value: "300"
      resources:
        limits:
          podman.io/device=/dev/dri/card1: 1
          podman.io/device=/dev/dri/renderD128: 1

    - name: redis
      image: docker.io/valkey/valkey:9@sha256:3b55fbaa0cd93cf0d9d961f405e4dfcc70efe325e2d84da207a0a8e6d8fde4f9
      livenessProbe:
        exec:
          command: ["redis-cli", "ping"]
        initialDelaySeconds: 30
        periodSeconds: 60

    - name: database
      image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0@sha256:bcf63357191b76a916ae5eb93464d65c07511da41e3bf7a8416db519b40b1c23
      env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: env
              key: DB_PASSWORD
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: env
              key: DB_USERNAME
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: env
              key: DB_DATABASE_NAME
        - name: POSTGRES_INITDB_ARGS
          value: "--data-checksums"
        # Uncomment the DB_STORAGE_TYPE: 'HDD' var if your database isn't stored on SSDs
        # - name: DB_STORAGE_TYPE
        #   value: "HDD"
      livenessProbe:
        exec:
          command:
            - /bin/sh
            - -c
            - pg_isready -d "$POSTGRES_DB" -U "$POSTGRES_USER"
        initialDelaySeconds: 30
        periodSeconds: 60
      volumeMounts:
        - name: db-data
          mountPath: /var/lib/postgresql/data
        - name: dshm
          mountPath: /dev/shm

  volumes:
    - name: upload-location
      hostPath:
        # Edit this line if UPLOAD_LOCATION in .env file changes
        path: /data/immich/library
        type: DirectoryOrCreate
    - name: db-data
      hostPath:
        # Edit this line if DB_DATA_LOCATION in .env file changes
        path: /data/immich/postgres
        type: DirectoryOrCreate
    - name: localtime
      hostPath:
        path: /etc/localtime
        type: Directory
    - name: dshm
      emptyDir:
        medium: Memory
        sizeLimit: 128Mi
