# Configuration file for Network UPS Tools drivers
# Backed up from /etc/nut/ups.conf

maxretry = 3

[cdp_ups]
    driver = nutdrv_qx
    port = auto
    vendorid = 0001
    productid = 0000
    subdriver = krauler
    protocol = megatec
    desc = "CDP R-Smart 751"
    ignorelb
    override.battery.charge.low = 80
