apiVersion: v1
kind: Pod
metadata:
  name: komga
spec:
  containers:
    - name: server
      image: ghcr.io/gotson/komga:1.x
      env:
        - name: JAVA_TOOL_OPTIONS
          value: "-XX:MaxRAMPercentage=75"
      envFrom:
        - configMapRef:
            name: env
      ports:
        - containerPort: 25600
          hostPort: 25600
      livenessProbe:
        httpGet:
          path: /actuator/health
          port: 25600
        initialDelaySeconds: 30
        periodSeconds: 30
        timeoutSeconds: 5
      volumeMounts:
        - name: config
          mountPath: /config
        - name: data
          mountPath: /data
      resources:
        limits:
          memory: "1Gi"
        requests:
          memory: "256Mi"

    - name: komf
      image: docker.io/sndxr/komf:1.7.1
      env:
        - name: JAVA_TOOL_OPTIONS
          value: "-XX:+UnlockExperimentalVMOptions -XX:+UseShenandoahGC -XX:ShenandoahGCHeuristics=compact -XX:ShenandoahGuaranteedGCInterval=3600000 -XX:TrimNativeHeapInterval=3600000"
      envFrom:
        - configMapRef:
            name: env
      ports:
        - containerPort: 8085
          hostPort: 8085
      volumeMounts:
        - name: komf-config
          mountPath: /config
      resources:
        limits:
          memory: "512Mi"
        requests:
          memory: "128Mi"

  volumes:
    - name: config
      hostPath:
        path: /data/komga/config
        type: DirectoryOrCreate
    - name: data
      hostPath:
        path: /data/komga/data
        type: DirectoryOrCreate
    - name: komf-config
      hostPath:
        path: /data/komga/komf
        type: DirectoryOrCreate
