apiVersion: v1
kind: Pod
metadata:
  name: minecraft
spec:
  containers:
    - name: server
      image: docker.io/itzg/minecraft-server:latest
      tty: true
      stdin: true
      securityContext:
        capabilities:
          add:
            - NET_RAW
      envFrom:
        - configMapRef:
            name: env
      ports:
        - containerPort: 25565
          hostPort: 25565
      volumeMounts:
        - name: data
          mountPath: /data
        - name: mods
          mountPath: /mods
        - name: config
          mountPath: /config
        - name: knockd-config
          mountPath: /tmp/knockd-config.cfg
          readOnly: true
    - name: playit
      image: ghcr.io/playit-cloud/playit-agent:0.17
      envFrom:
        - configMapRef:
            name: env.playit
          
  volumes:
    - name: data
      hostPath:
        path: /data/minecraft/data
        type: DirectoryOrCreate
    - name: mods
      hostPath:
        path: /data/minecraft/mods
        type: DirectoryOrCreate
    - name: config
      hostPath:
        path: /data/minecraft/config
        type: DirectoryOrCreate
    - name: knockd-config
      hostPath:
        path: /opt/minecraft/knockd-config.cfg
        type: File
