apiVersion: v1
kind: Pod
metadata:
  name: minecraft
spec:
  containers:
    - name: server
      image: docker.io/itzg/minecraft-server:latest
      tty: true
      stdin: true
      envFrom:
        - configMapRef:
            name: env
      ports:
        - containerPort: 25565
          hostPort: 25565
      volumeMounts:
        - name: data
          mountPath: /data
        - name: mods
          mountPath: /mods
        - name: config
          mountPath: /config
          
  volumes:
    - name: data
      hostPath:
        path: /data/minecraft/data
        type: DirectoryOrCreate
    - name: mods
      hostPath:
        path: /data/minecraft/mods
        type: DirectoryOrCreate
    - name: config
      hostPath:
        path: /data/minecraft/config
        type: DirectoryOrCreate
