apiVersion: v1
kind: Pod
metadata:
  name: vaultwarden
spec:
  containers:
    - name: server
      image: docker.io/vaultwarden/server
      envFrom:
        - configMapRef:
            name: env
      ports:
        - containerPort: 8080
          hostPort: 8080
      volumeMounts:
        - name: data
          mountPath: /data
      livenessProbe:
        exec:
          command:
          - /bin/sh
          - healthcheck.sh
        initialDelaySeconds: 10
        periodSeconds: 20
          
  volumes:
    - name: data
      hostPath:
        path: /data/vaultwarden
        type: DirectoryOrCreate
