apiVersion: v1
kind: Pod
metadata:
  name: it-tools
spec:
  containers:
    - name: web
      image: ghcr.io/corentinth/it-tools:latest
      ports:
        - containerPort: 80
          hostPort: 8082
