apiVersion: v1
kind: Pod
metadata:
  name: it-tools
spec:
  containers:
    - name: web
      image: ghcr.io/sharevb/it-tools:latest
      ports:
        - containerPort: 8080
          hostPort: 8082
